config/routes.rb
Rails.application.routes.draw do
  scope '/log', controller: :points do
    get '' => :log, as: :point_log
    get '/:subject' => :create, as: :point_create
  end

  resources :subjects

  get '/map/:subject' => 'points#map', as: :point_map

  get '/points/:subject' => 'points#index', as: :points
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/point.rb
class Point < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/points_controller.rb
class PointsController < ApplicationController
  def create
    params.require([:subject, :lat, :lon])

    extra_params = params.permit(:subject, :lat, :lon, :desc, :sat, :alt, :spd, :acc, :dir, :prov, :time,
                                 :start_time, :batt, :device_id, :serial, :act)
    extra_params[:time] ||= Time.now
    if extra_params[:start_time]
      extra_params[:start_time] = Time.at(extra_params[:start_time].to_i).utc.to_time
    end
    Point.create! extra_params
    head :no_content
  end

  def log
    render plain: point_create_url(subject: '') + '%AID?' +
        'lat=%LAT&lon=%LON&desc=%DESC&sat=%SAT&alt=%ALT&spd=%SPD&acc=%ACC&dir=%DIR&prov=%PROV&time=%TIME&start_time=%STARTTIMESTAMP&batt=%BATT&device_id=%AID&serial=%SERIAL&act=%ACT'
  end

  def map
    respond_to do |format|
      format.html {
        @subject = params.require(:subject)
        @points = Point.where(subject: @subject).where('time > ?', Time.now.beginning_of_day).order(:time).select(:lat, :lon).collect { |p| [p.lat, p.lon]}
        @lastPoint = Point.where(subject: @subject).order(id: :desc).first
      }
      format.json {
      }
    end

    render layout: false
  end

  def index
    @subject = params.require(:subject)
    @points = Point.where(subject: @subject).where('id > ?', params[:id]).order(:id)
    render json: @points
  end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController

  def index
    @subjects = Point.find_by_sql('select subject, max(time) as time, count(*) from points group by subject;')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/points_helper.rb
module PointsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Geotracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/points/map.html.erb
<html>
<head>

  <link rel="stylesheet" href="https://unpkg.com/leaflet@1.3.1/dist/leaflet.css"
        integrity="sha512-Rksm5RenBEKSKFjgI3a41vrjkw4EVPlJ3+OiI65vTjIdo9brlAacEuKOiQ5OFh7cOI1bkDwLqdLw3Zg0cRJAAQ=="
        crossorigin=""/>
  <link href='https://cdnjs.cloudflare.com/ajax/libs/leaflet.fullscreen/1.4.5/Control.FullScreen.css' rel='stylesheet' />
  <script src="https://unpkg.com/leaflet@1.3.1/dist/leaflet.js"
          integrity="sha512-/Nsx9X4HebavoBvEBuyp3I7od5tA0UzAxs+j83KgC8PU0kgB4XiK4Lfe4y4cgBtaRJQEIFCW+oC506aPT2L1zw=="
          crossorigin=""></script>
  <script src='https://cdnjs.cloudflare.com/ajax/libs/leaflet.fullscreen/1.4.5/Control.FullScreen.min.js'></script>
  <title>Camino / <%= Time.now.to_date %> / <%= @subject %></title>
  <style>
    html, body {
      height: 100%;
      margin:0;
      padding: 0;
    }
    #map {
      width: 100%;
      height: 100%;
    }
  </style>
</head>
<body>

<div id="map"></div>
<script type="application/javascript">
  var map = L.map('map', {
    fullscreenControl: true,
    fullscreenControlOptions: {
      position: 'topleft'
    }
  });
  //const tileUrl = 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png';
  //const tileUrl = 'https://{s}.tile.openstreetmap.de/tiles/osmde/{z}/{x}/{y}.png';
  const tileUrl = '/tiles/{z}/{x}/{y}.png';

  L.tileLayer(tileUrl, {
    attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
  }).addTo(map);
  L.control.scale().addTo(map);

  var latlngs = <%= @points.inspect %>;
  var lastPoint = <%= raw @lastPoint.try(:to_json) %>;
  var updatePath = '<%= points_path @subject %>';


  if(!latlngs || latlngs.length === 0) {
    latlngs = [[lastPoint.lat,lastPoint.lon]];
  }

  var polyline = L.polyline(latlngs, {color: 'red'}).addTo(map);
  map.fitBounds(polyline.getBounds());

  /** Distance code */
  var RADIUS = 6371;

  var toRad = function (n) {
    return n * Math.PI / 180;
  };

  var getDistance = function (from, to) {
    var fromLat = from[0];
    var fromLon = from[1];
    var toLat = to[0];
    var toLon = to[1];

    var dLat = toRad(toLat - fromLat);
    var dLon = toRad(toLon - fromLon);
    var fromLat = toRad(fromLat);
    var toLat = toRad(toLat);

    var a = Math.pow(Math.sin(dLat / 2), 2) +
      (Math.pow(Math.sin(dLon / 2), 2) * Math.cos(fromLat) * Math.cos(toLat));
    var c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));

    return RADIUS * c;
  };

  var measurePath = function (points) {
    return points.reduce(function (memo, point) {
      var distance = memo.lastPoint === null ? 0 : getDistance(memo.lastPoint, point);
      return {lastPoint: point, distance: distance + memo.distance};
    }, {lastPoint: null, distance: 0}).distance;
  };

  console.log(measurePath(latlngs));

  totalDistance = measurePath(latlngs);

  function markLastPoint(lastPoint) {
    if (lastPoint) {
      console.log("Last point:", lastPoint);
      var circle = L.circle([lastPoint.lat, lastPoint.lon], {
        color: 'red',
        fillColor: '#f03',
        radius: lastPoint.acc
      }).addTo(map);
      circle.bindPopup("Activity: " + lastPoint.act + " (" + (lastPoint.spd * 3.6).toPrecision(2) +
        "km/h), battery: " + lastPoint.batt +
        "%, measure: " + lastPoint.prov + ", accuracy: " +
        lastPoint.acc.toPrecision(3) + "m, Time: " + lastPoint.time +
        ", total distance: " + totalDistance.toPrecision(3) + "km");
    }
  }

  markLastPoint(lastPoint);

  /* Update code */

  function update() {
    window.fetch(updatePath + '?id=' + lastPoint.id + '&ts=' +  (new Date).getTime() ).then(function(response) {
        return response.json();
      }).
      then(function(json) {
        if(json && json.length > 0) {
          /*let ulatlons = json.map(p => L.latLng(p.lat, p.lon));
          console.log(ulatlons);*/
          json.forEach( x => {
            let latlng = L.latLng(x.lat, x.lon);
            polyline.addLatLng(latlng);
            //map.panTo(latlng);
            if(lastPoint) {
              totalDistance += getDistance([lastPoint.lat, lastPoint.lon], [x.lat, x.lon]);
            }
            lastPoint = x;
          });
          markLastPoint(lastPoint);
        }


    });
  }

  setInterval(update, 60000);


</script>

</body>
</html>

app/views/subjects/index.html.erb
<% @subjects.each do |s| %>
  <div>
  <%= link_to s.subject, point_map_path(s.subject) %>
  </div>
<% end %>